sudo: false
language: node_js
node_js:
  - node
after_success: 
  - npm run coverage
before_deploy:
  - npm install -g firebase-tools
  - npm run prepare
deploy:
  - firebase deploy --token $FIREBASE_TOKEN --only functions
notifications:
  email:
    - aman.chhabra1@gmail.com